import React, { Component } from 'react'

export class Task extends Component {
  render() {
    return (
        React.createElement('div',{class:"wrapper"},
        React.createElement('div',{class:"table basic"},
        React.createElement('div',{class:"price-section"},
        React.createElement('div',{class:"price-area"},
        React.createElement('div',{class:"inner-area"},
        React.createElement('span',{class:"price"},"$0/month")
        ))
        ),
        React.createElement('div',{class:"package-name"}),
        React.createElement('div',{class:"features"},
        React.createElement('li',null,
        React.createElement('span',{class:"list-name"},"Single User"),
        React.createElement('span',{class:"icon check"},
        React.createElement('i',{class:"fas fa-check-circle"}))),
        React.createElement('li',null,
        React.createElement('span',{class:"list-name"},"50GB storage"),
        React.createElement('span',{class:"icon check"},
        React.createElement('i',{class:"fas fa-check-circle"}))),
        React.createElement('li',null,
        React.createElement('span',{class:"list-name"},"Unlimited Public Projects"),
        React.createElement('span',{class:"icon check"},
        React.createElement('i',{class:"fas fa-check-circle"}))),
        React.createElement('li',null,
        React.createElement('span',{class:"list-name"},"Community Access"),
        React.createElement('span',{class:"icon check"},
        React.createElement('i',{class:"fas fa-check-circle"}))),
        React.createElement('li',null,
        React.createElement('span',{class:"list-cross"},"Unlimited Private Project"),
        React.createElement('span',{class:"icon cross"},
        React.createElement('i',{class:"fas fa-times-circle"}))),
        React.createElement('li',null,
        React.createElement('span',{class:"list-cross"},"Dedicated Phone Support"),
        React.createElement('span',{class:"icon cross"},
        React.createElement('i',{class:"fas fa-times-circle"}))),
        React.createElement('li',null,
        React.createElement('span',{class:"list-cross"},"Free Subdomain"),
        React.createElement('span',{class:"icon cross"},
        React.createElement('i',{class:"fas fa-times-circle"}))),
        React.createElement('li',null,
        React.createElement('span',{class:"list-cross"},"Monthly Status Reports"),
        React.createElement('span',{class:"icon cross"},
        React.createElement('i',{class:"fas fa-times-circle"}))),
        React.createElement('div',{class:"btn"},
        React.createElement('button',null,"Purchase")
        ))),
        React.createElement('div',{class:"table Premium"},
        React.createElement('div',{class:"price-section"},
        React.createElement('div',{class:"price-area"},
        React.createElement('div',{class:"inner-area"},
        React.createElement('span',{class:"price"},"$9/month")
        ))
        ),
        React.createElement('div',{class:"package-name"}),
        React.createElement('div',{class:"features"},
        React.createElement('li',null,
        React.createElement('span',{class:"list-name"},"5 Users"),
        React.createElement('span',{class:"icon check"},
        React.createElement('i',{class:"fas fa-check-circle"}))),
        React.createElement('li',null,
        React.createElement('span',{class:"list-name"},"50GB Storage"),
        React.createElement('span',{class:"icon check"},
        React.createElement('i',{class:"fas fa-check-circle"}))),
        React.createElement('li',null,
        React.createElement('span',{class:"list-name"},"Unlimited Public Project"),
        React.createElement('span',{class:"icon check"},
        React.createElement('i',{class:"fas fa-check-circle"}))),
        React.createElement('li',null,
        React.createElement('span',{class:"list-name"},"Community Access"),
        React.createElement('span',{class:"icon check"},
        React.createElement('i',{class:"fas fa-check-circle"}))),
        React.createElement('li',null,
        React.createElement('span',{class:"list-name"},"Unlimited Private Project"),
        React.createElement('span',{class:"icon check"},
        React.createElement('i',{class:"fas fa-check-circle"}))),
        React.createElement('li',null,
        React.createElement('span',{class:"list-name"},"Dedicated Phone Support"),
        React.createElement('span',{class:"icon check"},
        React.createElement('i',{class:"fas fa-check-circle"}))),
        React.createElement('li',null,
        React.createElement('span',{class:"list-name"},"Free Subdomain"),
        React.createElement('span',{class:"icon check"},
        React.createElement('i',{class:"fas fa-check-circle"}))),
        React.createElement('li',null,
        React.createElement('span',{class:"list-cross"},"Monthly Status Reports"),
        React.createElement('span',{class:"icon cross"},
        React.createElement('i',{class:"fas fa-times-circle"}))),
        React.createElement('div',{class:"btn"},
        React.createElement('button',null,"Purchase")
        ))),
        React.createElement('div',{class:"table Ultimate"},
        React.createElement('div',{class:"price-section"},
        React.createElement('div',{class:"price-area"},
        React.createElement('div',{class:"inner-area"},
        React.createElement('span',{class:"price"},"49$/month")
        ))
        ),
        React.createElement('div',{class:"package-name"}),
        React.createElement('div',{class:"features"},
        React.createElement('li',null,
        React.createElement('span',{class:"list-name"},"Unlimited Users"),
        React.createElement('span',{class:"icon check"},
        React.createElement('i',{class:"fas fa-check-circle"}))),
        React.createElement('li',null,
        React.createElement('span',{class:"list-name"},"50GB Storage"),
        React.createElement('span',{class:"icon check"},
        React.createElement('i',{class:"fas fa-check-circle"}))),
        React.createElement('li',null,
        React.createElement('span',{class:"list-name"},"Unlimited Public Project"),
        React.createElement('span',{class:"icon check"},
        React.createElement('i',{class:"fas fa-check-circle"}))),
        React.createElement('li',null,
        React.createElement('span',{class:"list-name"},"Community Access"),
        React.createElement('span',{class:"icon check"},
        React.createElement('i',{class:"fas fa-check-circle"}))),
        React.createElement('li',null,
        React.createElement('span',{class:"list-name"},"Unlimited Private Project"),
        React.createElement('span',{class:"icon check"},
        React.createElement('i',{class:"fas fa-check-circle"}))),
        React.createElement('li',null,
        React.createElement('span',{class:"list-name"},"Dedicated Phone Support"),
        React.createElement('span',{class:"icon check"},
        React.createElement('i',{class:"fas fa-check-circle"}))),
        React.createElement('li',null,
        React.createElement('span',{class:"list-name"},"Free Subdomain"),
        React.createElement('span',{class:"icon check"},
        React.createElement('i',{class:"fas fa-check-circle"}))),
        React.createElement('li',null,
        React.createElement('span',{class:"list-name"},"Monthly Status Reports"),
        React.createElement('span',{class:"icon check"},
        React.createElement('i',{class:"fas fa-check-circle"}))),
        React.createElement('div',{class:"btn"},
        React.createElement('button',null,"Purchase")
        )))

        )
    )
  }
}

export default Task